'use strict';

// tests for readuser
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('readuser', '/handler.js', 'readuser');
// Create default event
let event = {
  httpMethod: 'get',
  path: '/readuser',
  body: {},
  headers: {
    'Content-Type': 'application/json'
  }
}
describe('readuser', () => {
  before((done) => {
    done();
  });

  it('returns a single user', () => {
    // Customize event
    let _event = Object.assign({},event,{
      path: '/emilie.poulsen@example.com'
    })  	
    return wrapped.run(_event).then((response) => {
	  const body = JSON.parse(response.body);
	  expect(response.statusCode).to.be.equal(200);    	
      expect(response).to.not.be.empty;
    });
  });
});
